# Generated by Django 4.2.4 on 2023-09-28 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Excel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(default='Nepal', editable=False, max_length=5)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipalities', to='api.district')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('Province 1', 'Koshi'), ('Province 2', 'Madhesh'), ('Province 3', 'Bagmati'), ('Province 4', 'Gandaki'), ('Province 5', 'Lumbini'), ('Province 6', 'Karnali'), ('Province 7', 'Sudurpashchim')], max_length=10)),
                ('name', models.CharField(choices=[('Province 1', 'Koshi'), ('Province 2', 'Madhesh'), ('Province 3', 'Bagmati'), ('Province 4', 'Gandaki'), ('Province 5', 'Lumbini'), ('Province 6', 'Karnali'), ('Province 7', 'Sudurpashchim')], max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(blank=True, choices=[('On-Going', 'On-Going'), ('Completed', 'Completed')], max_length=20)),
                ('donor', models.CharField(blank=True, max_length=100)),
                ('executing_agency', models.CharField(blank=True, max_length=100)),
                ('implementing_partner', models.CharField(blank=True, max_length=100)),
                ('counterpart_ministry', models.CharField(blank=True, max_length=100)),
                ('type_of_assistance', models.CharField(blank=True, max_length=100)),
                ('budget_type', models.CharField(blank=True, choices=[('On Budget', 'On Budget'), ('Off Budget', 'Off Budget')], max_length=15)),
                ('humanitarian', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('agreement_date', models.DateField(blank=True)),
                ('commitments', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('disbursement', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('district', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.district')),
                ('municipality', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.municipality')),
                ('province', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.province')),
            ],
        ),
        migrations.AddField(
            model_name='municipality',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipalities', to='api.province'),
        ),
    ]
