# Generated by Django 4.2.4 on 2023-09-28 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_project_district_alter_project_municipality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='district',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.district'),
        ),
        migrations.AlterField(
            model_name='project',
            name='municipality',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.municipality'),
        ),
        migrations.AlterField(
            model_name='project',
            name='province',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.province'),
        ),
    ]
