# Generated by Django 4.2.4 on 2023-09-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_project_district_alter_project_municipality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='code',
            field=models.CharField(choices=[('Koshi Pradesh', 'Province 1'), ('Madhesh Pradesh', 'Province 2'), ('Bagmati Pradesh', 'Province 3'), ('Gandaki Pradesh', 'Province 4'), ('Lumbini Pradesh', 'Province 5'), ('Karnali Pradesh', 'Province 6'), ('Sudurpashchim Pradesh', 'Province 7')], max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(choices=[('Koshi Pradesh', 'Province 1'), ('Madhesh Pradesh', 'Province 2'), ('Bagmati Pradesh', 'Province 3'), ('Gandaki Pradesh', 'Province 4'), ('Lumbini Pradesh', 'Province 5'), ('Karnali Pradesh', 'Province 6'), ('Sudurpashchim Pradesh', 'Province 7')], max_length=30, unique=True),
        ),
    ]
